name = "ipos"
account_id = "b3f9fdfd827152316d080a5ddee59915"
main = "src/index.ts"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[vars]
S3_ACCESS_KEY_ID = ''
FILEBASE_BUCKET_NAME='koda-art'

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'stockpile'
preview_bucket_name = 'alpha-stockpile'

# beta environment
[env.beta]
name = 'ipos-beta'

[env.beta.vars]
S3_ACCESS_KEY_ID = ''
FILEBASE_BUCKET_NAME='koda-art'

[[env.beta.r2_buckets]]
binding = 'BUCKET'
preview_bucket_name = 'alpha-stockpile'

# production environment
[env.production]
name = 'ipos'

[env.beta.vars]
S3_ACCESS_KEY_ID = ''
FILEBASE_BUCKET_NAME='koda-art'

[[env.beta.r2_buckets]]
binding = 'BUCKET'
bucket_name = 'stockpile'
