name = "polysearch"
main = "src/index.ts"
compatibility_date = "2024-07-25"


[[d1_databases]]
binding = "POLYSEARCH_DB"
database_name = "multisearch"
database_id = "8aed80cb-fb9b-4532-8c13-82721ad99549"