name: Deploy to Cloudflare workers
run-name: Deploy "${{ inputs.worker }}-${{ inputs.environment }}" by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      worker:
        description: 'Name of the worker'
        required: true
        type: choice
        options: # please add manually if you add new worker
          - capture
          - counter
          - durable-jpeg
          - frame
          - image
          - keywise
          - newsletter
          - party
          - polysearch
          - price
          - scheduled
          - ssr-opengraph
      environment:
        description: 'Choose an environment'
        required: true
        type: choice
        default: 'beta'
        options:
          - default
          - beta
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Publish (beta or production)
        if: github.event.inputs.environment == 'beta' || github.event.inputs.environment == 'production'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: ./services/${{ github.event.inputs.worker }}
          command: publish --env ${{ github.event.inputs.environment }}

      - name: Publish (default)
        if: github.event.inputs.environment != 'beta' && github.event.inputs.environment != 'production'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: ./services/${{ github.event.inputs.worker }}
