name: Test Endpoints

on:
  pull_request:
    branches: [main]

jobs:
  test-image-workers:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/image
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install
      - run: pnpm test
